### ISSUE TITLE
Issues parsing file with curly braces {{ }}

### ISSUE THREAD

**Issue by Lirt** [kislyuk/yq#115]
Hello,

I'm trying to parse yaml file with double curly brace pair (`{{ }}`). If the file contains a curly brace pair used for example in [helm](https://github.com/helm/helm/) or Go templating, it fails with error `yq: Error running jq: TypeError: unhashable type: 'collections.OrderedDict'`.

Here is example file you can try it on. 

```yaml
---
kind: test
metadata:
  name: test
spec:
  version: {{ .testVersion }}
```

`yq` version is `2.12.0`.

**Comment by Lirt** [comment]
It parses well when double curly braces are inside of string, so for example quoted like "{{ .testVersion }}", but also in case of yaml multi-line strings.

Which means this works for example.

```yaml
---
kind: test
metadata:
  name: test
spec:
  version: |
    {{ .testVersion }}
```
