### ISSUE TITLE
quote replaced yaml output?

### ISSUE THREAD

**Issue by JonGilmore** [kislyuk/yq#118]
lets take the following simple yaml file named `a.yml` that I'd like to modify:
```yaml
strategy: merge
hostname: corp.org.com
user: blah
```

I can replace the value in `user` easily like so:
`yq -y '.["user"] = "blah2"' a.yml`

But, if I want to quote the replaced value of `user`, I cannot seem to find out a way to do this. For example, this `yq -y '.["user"] = "\"blah2\""' a.yml` yields:
```yaml
strategy: merge
hostname: corp.org.com
user: '"blah2"'
```

Any thoughts on how I could achieve this? Obviously, this is an over-simplified version of what I'm actually trying to do, the string that ends up in `user` will have reserved characters that I believe I need quoted.
