### ISSUE TITLE
Output of yq contains three dash (---) on Amazon Linux 2

### ISSUE THREAD

**Issue by macrovve** [kislyuk/yq#128]
Here is my YAML file `effectiveConfig.yaml`

```
---
system:
  certificateFilePath: "/greengrass/v2/thingCert.crt"
  privateKeyPath: "/greengrass/v2/privKey.key"
  rootCaPath: "/greengrass/v2/rootCA.pem"
  rootpath: "/greengrass/v2"
  thingName: "test-1"
```

When I run below command on Amazon Linux 2, the output will contain `---`
```
[root@hostname ~]# yq e '.system.thingName' effectiveConfig.yaml
---
test-1
```

But If I run same command with same file on Ubuntu, the output won't contain `---`
```
root@hostname~# yq e '.system.thingName' effectiveConfig.yaml
test-1
```

Version for Ubuntu: 

```
$ yq -V
yq version 4.9.6
```

Version for Amazon Linux 2

```
# yq -V
yq (https://github.com/mikefarah/yq/) version 4.10.0
```
