### ISSUE TITLE
Add indentation & improve sorting of TOML output

### ISSUE THREAD

**Issue by oleole39** [kislyuk/yq#164]
Hello,

Thank you for sharing and maintaining this tool.

Would you consider adding an option (either default behavior or by specifying a parameter) to indent toml output in a way similar to https://github.com/kislyuk/yq/issues/52, and improve the way `toml` sorts the keys ?

Currently, with yq/tomlq 3.1.1, if my toml file is as follows:
```toml
[cat1]
prop1 = false

    [cat1.sucat]
    prop1 = false

        [cat1.subcat.subsubcat]
        prop1 = true
        prop2 = "hello"

[cat2]
prop1 = false
```

Running `cat my-example.toml | tomlq - t ` outputs:

```toml
[cat1]
prop1 = false

[cat2]
prop1 = false

[cat1.sucat]
prop1 = false

[cat1.subcat.subsubcat]
prop1 = true
prop2 = "hello"
```
Somehow `tomlq` decided to sort keys differently and did not leave keys and subkeys following each other (sounding a bit counterintuitive to me).
I also personally find the lack of indentation less readable, and that does not match the "official" formatting used in the example displayed on [toml language's repo's readme](https://github.com/toml-lang/toml#example):

```toml
# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
```
Running `cat official-example.toml | tomlq - t` outputs:

```toml
title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = "1979-05-27T07:32:00-08:00"

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002,]
connection_max = 5000
enabled = true

[clients]
data = [ [ "gamma", "delta",], [ 1, 2,],]
hosts = [ "alpha", "omeg",]

[servers.alpha]
ip = "10.0.0.1"
dc = "eqdc10"

[servers.beta]
ip = "10.0.0.2"
dc = "eqdc10"
```
We can see `tomlq` deleted comments (maybe this would be more complicated to avoid?) and removed `[servers]` category header probably because it considered it was an empty key, disregarding its subkeys.  

Best regards,
oleole39
