### ISSUE TITLE
xml: is keeping the namespace possible?

### ISSUE THREAD

**Issue by elandorr** [kislyuk/yq#169]
Hi

is it possible to keep the ns here?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<foo>
    <title>barfoo</title>
    <macroni:title>foobar</macroni:title>
</foo>
```

The `macroni` is lost.

```yml
+p_xml: version="1.0" encoding="UTF-8"
foo:
  title:
    - barfoo
    - foobar
```

I have a file that uses such a format, which means this borks:

```
yq -pxml -oy '.foo.title' fooo.xml 

- barfoo
- foobar
```

Ideally it would only show the `<title>`.

Appreciate yq, really useful, thanks!
