### ISSUE TITLE
Toml error

### ISSUE THREAD

**Issue by elibroftw** [kislyuk/yq#178]
python3 -m yq '.workspace[]' Cargo.toml 

jq: error (at <stdin>:1): Cannot index array with string "workspace

```toml
[workspace]
resolver = "2"
```
