### ISSUE TITLE
01-07 as Base 8 , expect 08-09 as str, but got Error

### ISSUE THREAD

**Issue by Peter33333** [kislyuk/yq#201]
```
applications:
  prod:
    alumniwebappcas2:
      services:
        nodejs:
          instances:
            08:
              cloud_provider: "hci"
              cpus: 1
              ramGB: 2
              diskGB: 50
          app_version: "1.5.0"
    alumniwebappcas:
      services:
        nodejs:
          instances:
            !!str 09:
              cloud_provider: "hci"
              cpus: 1
              ramGB: 2
              diskGB: 50
          app_version: "1.5.0"
  uat:
    alumniwebappcas:
      services:
        nodejs:
          instances:
            !!int "011":
              cloud_provider: "hci"
              cpus: 1
              ramGB: 2
              diskGB: 50
          app_version: "1.5.0"


```
yq: Error running jq: ValueError: invalid literal for int() with base 8: '08'.
