### ISSUE TITLE
preserve/restore indentation

### ISSUE THREAD

**Issue by drzraf** [kislyuk/yq#29]
input.yml:
```yaml
a: b
c:
  - d
```

Command:
`yq -y '.c += ["e"]' input.yml`

Output:
```
a: b
c:
- d
- e
```

Expect output:
```
a: b
c:
  - d
  - e
```
