### ISSUE TITLE
Enable configurable indentation

### ISSUE THREAD

**Issue by AnthonyWC** [kislyuk/yq#52]
e.g.

foo.json
```
{
  "test": {
    "s1": "bar",
    "s2": [
      "snowflake",
      "s3",
      "gcloud"
    ]
  }
}
```

`yq -y . foo.json`

```
test:
  s1: bar
  s2:
  - snowflake
  - s3
  - gcloud
```

When valid yaml should be:
```
 test:
   s1: bar
   s2:
     - snowflake
     - s3
     - gcloud
```
