### ISSUE TITLE
--yaml-output breaks yaml file format

### ISSUE THREAD

**Issue by jean-christophe-manciot** [kislyuk/yq#93]
yq: 2.10.0
With the following input yaml file ```yaml_list_dict.yml```:
```
---
yaml_struct:
  - key_1: '$.*?/|\^(){}+@[]&_-'
    key_2:
      - '$.*?/|\^(){}+@[]&_-'
      - "{\_}"
      - value23
    key_3: value31
    key_4:
      - value41
      - value42
    key_5: value51
  - key_1_: value12
    _key_2:
      - value24
      - value25
    _key__3: '$.*?/|\^(){}+@[]&_-'
...
```
The following command breaks the original format:
```
yq --sort-keys --yaml-output . ./yaml_list_dict.yml
yaml_struct:
  - key_1: $.*?/|\^(){}+@[]&_-
    key_2:
      - $.*?/|\^(){}+@[]&_-
      - '{ }'
      - value23
    key_3: value31
    key_4:
      - value41
      - value42
    key_5: value51
  - _key_2:
      - value24
      - value25
    _key__3: $.*?/|\^(){}+@[]&_-
    key_1_: value12
```
The original ```---`` and ```...``` have been removed.
Am I missing something?
