### ISSUE TITLE
Question - How can I replace an element of a list?

### ISSUE THREAD

**Issue by vikas027** [kislyuk/yq#94]
I am trying to replace `rolearn` in the below yaml with a value, I've read the docs but could not figure out how to replace `rolearn` here.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
```
